on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: wangchaoyi/qcloud-cos-deploy-action@main
        with:
          secret_id: ${{ secrets.QCLOUD_COS_SECRET_ID }}
          secret_key: ${{ secrets.QCLOUD_COS_SECRET_KEY }}
          token: ""
          buckets: ${{ secrets.QCLOUD_COS_BUCKETS }}
          region: ap-shanghai
      - run: cat ~/.cos.yaml && coscli ls cos://${{ secrets.QCLOUD_COS_BUCKETS }}
        shell: bash